const gameData = {
  "id": 85,
  "hostId": 23,
  "date": "2022-12-29",
  "transportRequired": false,
  "hostName": "Malcolm Reynolds",
  "seasonId": 3,
  "quarter": "THIRD",
  "seasonGameNum": 34,
  "quarterlyGameNum": 9,
  "kittyCost": 0,
  "buyInCost": 40,
  "rebuyAddOnCost": 40,
  "rebuyAddOnTocDebitCost": 20,
  "annualTocCost": 20,
  "quarterlyTocCost": 20,
  "buyInCollected": 320,
  "rebuyAddOnCollected": 80,
  "annualTocCollected": 120,
  "quarterlyTocCollected": 40,
  "totalCollected": 560,
  "annualTocFromRebuyAddOnCalculated": 40,
  "rebuyAddOnLessAnnualTocCalculated": 40,
  "totalCombinedTocCalculated": 200,
  "kittyCalculated": 0,
  "prizePotCalculated": 360,
  "numPlayers": 8,
  "numPaidPlayers": 8,
  "started": null,
  "lastCalculated": "2022-12-26T20:33:23",
  "chopped": false,
  "canRebuy": true,
  "finalized": false,
  "payoutDelta": 0,
  "players": [
  {
    "id": 962,
    "playerId": 9,
    "gameId": 85,
    "boughtIn": true,
    "rebought": false,
    "annualTocParticipant": true,
    "quarterlyTocParticipant": true,
    "roundUpdates": false,
    "place": 8,
    "knockedOut": true,
    "chop": null,
    "seasonId": 3,
    "firstName": "Zoë",
    "lastName": "Washburne",
    "email": "ZoeWashburne@example.com",
    "phone": "5125551212",
    "tocPoints": 10,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": null,
    "annualTocCollected": 20,
    "quarterlyTocCollected": 20,
    "qtocPoints": 10,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "Zoë Washburne"
  },
  {
    "id": 955,
    "playerId": 1,
    "gameId": 85,
    "boughtIn": true,
    "rebought": true,
    "annualTocParticipant": true,
    "quarterlyTocParticipant": false,
    "roundUpdates": false,
    "place": 11,
    "knockedOut": false,
    "chop": null,
    "seasonId": 3,
    "firstName": "Hoban",
    "lastName": "Washburne",
    "email": "HobanWashburne@example.com",
    "phone": null,
    "tocPoints": null,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": 40,
    "annualTocCollected": 20,
    "quarterlyTocCollected": null,
    "qtocPoints": null,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "Hoban Washburne"
  },
  {
    "id": 956,
    "playerId": 4,
    "gameId": 85,
    "boughtIn": true,
    "rebought": false,
    "annualTocParticipant": true,
    "quarterlyTocParticipant": true,
    "roundUpdates": true,
    "place": 11,
    "knockedOut": false,
    "chop": null,
    "seasonId": 3,
    "firstName": "Inara",
    "lastName": "Serra",
    "email": "InaraSerra@example.com",
    "phone": "5125551212",
    "tocPoints": null,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": null,
    "annualTocCollected": 20,
    "quarterlyTocCollected": 20,
    "qtocPoints": null,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "Inara Serra"
  },
  {
    "id": 957,
    "playerId": 34,
    "gameId": 85,
    "boughtIn": true,
    "rebought": true,
    "annualTocParticipant": true,
    "quarterlyTocParticipant": false,
    "roundUpdates": false,
    "place": 11,
    "knockedOut": false,
    "chop": null,
    "seasonId": 3,
    "firstName": "Jayne",
    "lastName": "Cobb",
    "email": null,
    "phone": null,
    "tocPoints": null,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": 40,
    "annualTocCollected": 20,
    "quarterlyTocCollected": null,
    "qtocPoints": null,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "Jayne Cobb"
  },
  {
    "id": 958,
    "playerId": 6,
    "gameId": 85,
    "boughtIn": true,
    "rebought": false,
    "annualTocParticipant": true,
    "quarterlyTocParticipant": false,
    "roundUpdates": false,
    "place": null,
    "knockedOut": false,
    "chop": null,
    "seasonId": 3,
    "firstName": "Kaylee",
    "lastName": "Frye",
    "email": "KayleeFrye@example.com",
    "phone": "5125551212",
    "tocPoints": null,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": null,
    "annualTocCollected": 20,
    "quarterlyTocCollected": null,
    "qtocPoints": null,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "Kaylee Frye"
  },
  {
    "id": 959,
    "playerId": 68,
    "gameId": 85,
    "boughtIn": true,
    "rebought": false,
    "annualTocParticipant": false,
    "quarterlyTocParticipant": false,
    "roundUpdates": false,
    "place": null,
    "knockedOut": false,
    "chop": null,
    "seasonId": 3,
    "firstName": "Simon",
    "lastName": "Tam",
    "email": null,
    "phone": null,
    "tocPoints": null,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": null,
    "annualTocCollected": null,
    "quarterlyTocCollected": null,
    "qtocPoints": null,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "Simon Tam"
  },
  {
    "id": 960,
    "playerId": 62,
    "gameId": 85,
    "boughtIn": true,
    "rebought": false,
    "annualTocParticipant": false,
    "quarterlyTocParticipant": false,
    "roundUpdates": false,
    "place": null,
    "knockedOut": false,
    "chop": null,
    "seasonId": 3,
    "firstName": "River",
    "lastName": "Tam",
    "email": "RiverTam@example.com",
    "phone": null,
    "tocPoints": null,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": null,
    "annualTocCollected": null,
    "quarterlyTocCollected": null,
    "qtocPoints": null,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "River Tam"
  },
  {
    "id": 961,
    "playerId": 8,
    "gameId": 85,
    "boughtIn": true,
    "rebought": false,
    "annualTocParticipant": true,
    "quarterlyTocParticipant": false,
    "roundUpdates": false,
    "place": null,
    "knockedOut": false,
    "chop": null,
    "seasonId": 3,
    "firstName": "Shepherd",
    "lastName": "Book",
    "email": "ShepherdBook@example.com",
    "phone": "5125551212",
    "tocPoints": null,
    "tocChopPoints": null,
    "buyInCollected": 40,
    "rebuyAddOnCollected": null,
    "annualTocCollected": 20,
    "quarterlyTocCollected": null,
    "qtocPoints": null,
    "qtocChopPoints": null,
    "qseasonId": 11,
    "name": "Shepherd Book"
  }
],
  "payouts": [
  {
    "id": 6500,
    "gameId": 85,
    "place": 1,
    "amount": 234,
    "chopAmount": null
  },
  {
    "id": 6501,
    "gameId": 85,
    "place": 2,
    "amount": 126,
    "chopAmount": null
  }
],
  "seating": null,
  "qseasonId": 11
}

export default gameData;